### ISSUE TITLE
Calling save() only saves every 2nd time

### ISSUE THREAD

**Issue by aimeemay** [firebase/emberfire#144]
Calling ```NewPost.save()``` works fine.

Calling ```this.get('model').save()``` only saves every 2nd time while returning 'success' each time. Then when refreshing the page, does not save at all returning neither 'success' or 'failure'. 

My controller 
``` javascript
var _this = this;

var newPost = _this.store.createRecord('post', {
              title: _this.get('postTitle'),
          });

          //save post
          var newPostPromise = newPost.save();
          
          //add post to issue and save issue
          //this.get('model') is the issue
          var modelPromise = _this.get('model.posts').addObject(newPost);
          _this.get('model').save();

          // Check if post save successful
            newPostPromise.then(function(a){
              alert('success')
            }, function(a){
              alert('failure');
            })

          // Check if model save successful
          modelPromise.then(function(a){
            alert('success')
          }, function(a){
            alert('failure');
          })
```

My model
``` javascript
App.Post = DS.Model.extend({
  title: DS.attr(''),
  issue: DS.belongsTo('issue', { async: true })
});

App.Issue = DS.Model.extend({
  title: DS.attr(''),
  posts: DS.hasMany('post', { async: true })
});
```

**Comment by sararob** [comment]
@aimeemay are you still having issues with this?

**Comment by tstirrat** [comment]
This appears to be working fine in the latest version. 

You were doing a couple of things that might have been causing some problems:

- Use `console.log` instead of `alert`. `alert` is usually problematic when debugging.
- You were saving the post before it had any knowledge of the link to the parent issue, so once you save the issue the models on the server were out of sync with their inverse relationship links
- `modelPromise` is not actually a the promise of the save action, it is the result of the `.get('posts')` action so it was probably always resolving with 'success` earlier than you expected.

It's a good idea when working with `hasMany` relationships to save in this order (due to the way `ember-data` likes to keep the inverse side of your relationships in sync):

1. Create child record
1. Add child to the `hasMany` array of parent with `addObject`/`pushObject`
1. Save child record
1. (in `.then` callback) Save parent record

e.g.:

```js
  actions: {
    create() {
      var newPost = this.store.createRecord('post', {
        title: this.get('postTitle')
      });

      var issue = this.get('model');
      issue.get('posts').addObject(newPost);

      newPost.save()
        .then(() => {
          return issue.save();
        })
        .catch((e) => {
          console.error('save: failure', e);
        });
    }
  }
```

If you try to save the parent first in recent versions of `ember-data` you can will see a weird duplicate record until the model is reloaded.. I think this is a bug in `ember-data` but need to investigate more.
