### ISSUE TITLE
Design: how are relationships supposed to work?

### ISSUE THREAD

**Issue by oskarrough** [firebase/emberfire#147]
Hi, how are hasMany/belongsTo relationships supposed to work? If I delete a post model that belongs to a user model, is the relationship automatically deleted on the user as well or is it something you do manually?

Another example, you delete a post that many different users "liked" - are those likes removed with the post? Or should I iterate through all users, find the post from their likes and delete the reference?

**Comment by oskarrough** [comment]
Would love some documentation on this as I can't guess how it's supposed to work. By deleting a record I'm seeing hasMany relationships removed automatically but not persisted. Is this good or bad?

Say I want to delete a tweet. A tweet can be favorited by users and belongsTo one user. How would the code look like? Do you need to remove all relationships yourself or only some, which?

cc @tstirrat @sararob





cc @tstirrat @sararob

**Comment by hugovieilledent** [comment]
Also interested in a clarification

**Comment by tstirrat** [comment]
To answer your first question:

as of #181 we are now removing `hasMany` links when deleting "child" records in a `hasMany` <-> `belongsTo` relationship. This will only work, however, if you have the relationship defined on both sides:

```js
// app/models/user.js
export default DS.Model.extend({
  name: DS.attr('string'),
  posts: DS.hasMany('post'),
});

// app/models/post.js
export default DS.Model.extend({
  user: DS.belongsTo('user'), // <-- this must be defined
  title: DS.attr('string'),
  body: DS.attr('string')
});

/* user:
{
  name: 'tim',
  posts: {
    '-Jjaxt6AgCi_s4Pldzzi': true
  }
}
*/

post.destroyRecord().then(function () {
  /* user:
  {
    name: 'tim',
  }
  */
});
```

**Comment by tstirrat** [comment]
For the second question:

> Another example, you delete a post that many different users "liked" - are those likes removed with the post? Or should I iterate through all users, find the post from their likes and delete the reference?

If you have specifics of how you've modeled it, it would be great to see your implementation. We can start working out a good way to handle these more complex relationships.

Something that should work, because it uses an intermediate model and two `hasMany` <-> `belongsTo` relationships:

```js
// app/models/user.js
export default DS.Model.extend({
  name: DS.attr('string'),
  posts: DS.hasMany('post'),
  favorites: DS.hasMany('favorite')
});

// app/models/favorite.js
export default DS.Model.extend({
  user: DS.belongsTo('user'),
  post: DS.belongsTo('post')
});

// app/models/post.js
export default DS.Model.extend({
  user: DS.belongsTo('user'),
  title: DS.attr('string'),
  body: DS.attr('string'),
  favorites: DS.hasMany('favorite')
});
```

In this situation, if you deleted the `post`, it would leave an invalid `favorite` (because we don't clean `belongsTo` links, yet). It would be cleaner to find the relevant `favorite` and delete it. 

*In theory*, this will remove the `hasMany` link in `user.favorites` and `post.favorites` from the server. I will make a test of this pattern to confirm if this does actually work.

I am finding a few things with relationships that need some work and will be fixing them over the coming weeks.

**Comment by oskarrough** [comment]
@tstirrat, thanks so much for improving the adapter and clarifying. It helps. Got lots of questions but here's one; In the second example, you'd do something like this?

```JavaScript
post.destroyRecord().then(function() {
	// we need to remove each favorite manually because it's a hasMany<>belongsTo relationship
	// (Emberfire only removes hasMany<>hasMany automatically)
	post.get('favorites').then(function(favorites) {
		favorites.forEach(function(fav) {
			fav.destroyRecord();
		});
	});
});```

**Comment by tstirrat** [comment]
almost, remove favorites first. Until i can add some logic to handle orphaned `belongsTo` links.

Something like this. I'm being incredibly defensive here to make sure all `favorite`s are deleted before the `post` begins deleting.

```js
post.get('favorites').then(function(favorites) {
  var deleteFavorites = favorites.map(function(fav) {
    return fav.destroyRecord();
  });

  Ember.RSVP.allSettled(deleteFavorites).then(function (results) {
    var rejected = Ember.A(results).filterBy('state', 'rejected');
    if (rejected.get('length') === 0) {
      return post.destroyRecord();
    }
    // eek: something went wrong, at least one fav was not correctly destroyed
  });
});
```

**Comment by jakecraige** [comment]
@tstirrat As a heads up, you can do that last part like this instead. `RSVP.all` will reject if any of the promises reject. So this is equivalent to your example. but without the filter and conditional. 

```js
Ember.RSVP.all(deleteFavorites).then(function () {
  return post.destroyRecord();  
}).catch(funtion (err) {
  // eek: something went wrong, at least one fav was not correctly destroyed
});

**Comment by tstirrat** [comment]
Ah yes, much cleaner.

**Comment by nigelsmith** [comment]
Thanks for the work on Emberfire.  I also wish the documentation was a little more detailed and, in particular, focussed on expected behaviour rather than just a relatively brief description of each item.

To make sure I understand the current situation, when creating records with a hasMany --> belongs relationship it's necessary to explicitly save each side - emberfire won't undertake this for you?

For example, in a classic blog post / comments situation:

```js
var newComment = this.get('comment');
var post = this.get('model');

post.get('comments').createRecord({
  content: 'foo',
  post: post
}).save();
post.save();
```

and only by doing that do you end up with:

```json
{
  "postTitle": "foo",
  "comments": {
    "newCommentID": true
  }
}

{
  "content": "foo",
  "post": "postID"
}
```

?

**Comment by tstirrat** [comment]
@nigelsmith yes, you should save both sides yourself, emberfire does not try to save associated records unless it is an **embedded** record.

I will make a push for better documentation on this

**Comment by nigelsmith** [comment]
Many thanks @tstirrat :)

**Comment by Ghostavio** [comment]
nice to see all the improvements :)

**Comment by jamesdixon** [comment]
@nigelsmith @tstirrat interesting that you mentioned saving both sides. I was under the same assumption when creating records with a hasMany --> belongsTo relationship, but while doing some debugging, I noticed that I only had to save one side in order for the relationship to be saved to both models. Has something changed? I'm using EmberFire 1.4.4 and Ember Data 1.0.0-beta.16.1.

**Comment by tstirrat** [comment]
If you save on one side it will still work due to the way ember data reconciles relationships. Basically, if you have a `hasMany` entry saved on the server, ember will auto update the inverse `belongsTo` when the record is deserialized from the server (unless you define `{ inverse: null }`)

In the same way that a child's `belongsTo` is auto updated when you do `parent.get('children').addObject(child)` .. this same relationship reconcilliation process is happening when new records are pushed into the store.

This is why it appears to work when you save the child before it is added to the `hasMany` array. As long as you save the parent, the parent's `hasMany` entry will help link up the child's `belongsTo` property, however the child's `belongsTo` property will actually be missing in Firebase.

It is most likely to counteract some REST API's that prefer to define the `hasMany <-> belongsTo` relationships on one side only.

**Comment by gabrielgrant** [comment]
The extra manual tracking that Emberfire requires around relationships is a real footgun. Now that [multi-location atomic writes are supported](https://www.firebase.com/blog/2015-09-24-atomic-writes-and-more.html) it seems Emberfire should make use of those to just automatically update both sides of a relationship.

**Comment by tstirrat** [comment]
I'd welcome a PR with an attempt at multi-location writes to keep `async` relationships in sync, but be sure to test lots of edge cases. There will be fighting with Ember Data's internal relationship reconciliation.

e.g. you'll need to test all sorts of things like deleting links and re adding them to make sure there are no duplicates left on the client. These artifacts/ghosts aren't always the easiest to find in integration tests. 

As for embedded relationships. I'm hoping it will be solved by always writing the entire object in one go with this new branch: [serialize-relationships-atomic](https://github.com/firebase/emberfire/tree/serialize-relationships-atomic)
