### ISSUE TITLE
Error: Could not find module ember-data

### ISSUE THREAD

**Issue by brendanoh** [firebase/emberfire#171]
Error while processing route: demo Could not find module ember-data Error: Could not find module ember-data.

When I try with 1.9.1 and beta 12 within Ember-CLI I get the error above and of course it doesn't work. Keep coming back and trying to use EmberFire in a project and it never works first try. Very frustrated.

If I am using Ember-CLI what are the latest versions of Ember and Ember-Data actually work with EmberFire?

Food for thought:
AngularFire     13 open     336 closed
EmberFire       25 open       90 closed

**Comment by brendanoh** [comment]
Tried cloning the ember-cli-emberfire project and upgrading it to match my project.

handlebars.js:455 Uncaught Error: Unknown template object: functionhandlebars.js:455 templatehandlebars.js:644 hb.templateloading.js:5 (anonymous function)

I thought it was Handlebars 2 but even with 1.3 and Ember 1.8.1 & CLI 0.1.9 it stills bombs.

**Comment by oskarrough** [comment]
This doesn't sound like an emberfire bug but if you want Handlebars 2.0.0 and Ember 1.9.1 with ember-cli, please see this post: http://emberjs.com/blog/2014/12/08/ember-1-9-0-released.html

Since ember-cli-emberfire isn't up-to-date you could try using bower for firebase+emberfire and including them the normal way in your `Brocfile.js.`

**Comment by brendanoh** [comment]
@oskarrough This doesn't sound like an emberfire bug?

"Error while processing route: demo Could not find module ember-data Error: Could not find module ember-data."

My project already worked fine with Handlebars 2, Ember Canary and Ember-Data Canary with fixture or rest adapter. Install EmberFire and try to use the Firebase adapter and now that error is there.

Looks like an EmberFire issue to me.

My question is the real point of this issue: If I am using Ember-CLI what are the latest versions of Ember and Ember-Data actually work with EmberFire?

If it takes 20 hours to get this working then it feels like it isn't really actively supported by Firebase but is just something they do so it doesn't seem like all they support is Angular.

**Comment by oskarrough** [comment]
Definitely, and Emberfire hasn't recieved any improvements since October 2014 (https://github.com/firebase/emberfire/pull/149). Since Google bought Firebase I'm worried that Emberfire will continue to wither away.

That being said, and even considering there's still no support for findQuery, it's possible to build lots of things with Emberfire already.

I just tried a new install of ember-cli@0.1.9 with emberfire 1.3.2 where I'm not seeing your issue. I did the following:

```bash
ember new whatever
bower install --save handlebars#2.0.0
bower install --save emberfire 
npm uninstall --save-dev broccoli-ember-hbs-template-compiler
npm install --save-dev ember-cli-htmlbars
```

and then added these to my `Brocfile.js`:

```
app.import('bower_components/firebase/firebase.js');
app.import('bower_components/emberfire/dist/emberfire.js');```

Just tried it again where it works for me. Could you post your setup somehow?

**Comment by brendanoh** [comment]
@oskarrough thanks for the response. this is the third time I have tried to use EmberFire in an app and every time it seems to have some new issue. Combine that with the fact that it was working before had me convinced that it was EmberFire.

I will follow the process you outline above and see where I get to. 

Thanks again.

**Comment by davideast** [comment]
@brendanoh @oskarrough 

Thanks for the feedback on this issue. 

I wanted to let you guys know that we are planning improvements and new features for EmberFire. @sararob and new Firebaser @tstirrat are going to work on getting a new release out that fix many of the open issues.

Ember is an important part of the Firebase community. We are sponsoring EmberConf for the second year in row. 

AngularFire is very active, but it's not the only active library. I own the BackboneFire library which is consistently updated, and the ReactFire library is actively maintained as well.

Please keep opening issues and keep us on our toes. We'll get updates pushed out soon.
