### ISSUE TITLE
Serious Firebase / EmberFire / Firebase Hosting Question 

### ISSUE THREAD

**Issue by brendanoh** [firebase/emberfire#176]
I love the serverless pattern and Firebase Hosting is great but without the ability to really send queries I dont see how anyone could build anything substantial using EmberFire.

Let's assume I have an App that needs to do more that just Select by ID and Select All

How do you use this library if you cannot query Firebase?
Is there a way to pass native queries in via the data adapter?

Lets assume I have a user and I want to show all of his Posts but the Firebase repository has more than just his posts stored there. I cannot figure out how to pass in a query param (user = 5) to make that work in a normal way. There doesn't seem to be a way to Sideload either. One thing I can do is if the user has an array of Post Ids in their user model then I can iterate over them and make dozens of API calls into Firebase to get each post but that seems awful.

Please someone tell me I am missing something that makes this all possible and EmberFire worthwhile. 

Brendan

**Comment by eibrahim** [comment]
I agree... it is tough... The way I have been doing it is using ember data belongsto and hasmany and it handles the relationship for me...  underneath, i think it does a for loop and gets each one indivdually - not sure.

for example, I get a project by ID... this has a hasMany(tasks)...  ember will then load all the tasks for it by *** i think *** looping over the project.tasks array of task IDs and getting 1 task at a time...  I haven't noticed a performance hit and ember data makes it really easy - but my coworker is writing the same code in angular and he is having to do a lot of that manually - a REAL PAIN...

**Comment by katowulf** [comment]
Brendan,

I'll be closing this issue as a duplicate since a) substantial apps function without queries and b) the request to add queries has [already been discussed here](https://github.com/firebase/emberfire/issues/66). Be sure to check out that link as there are already some solutions and workarounds available.

If nothing there meets your needs, it's not trivial, but also not particularly challenging, to implement your own find() method or DS.Store that utilizes a query. You can drop to the Firebase API and use it directly at any time when you reach the limitations of EmberFire. 

If you do hack together your own methods, you should circle back and share them with the community, as they are likely to benefit others (and PRs would, of course, be magnificent).

Cheers,
Kato

**Comment by brendanoh** [comment]
@katowulf if it is "not particularly challenging" then where is an example I can see? 

I have read the other issues related to this but this question was not 'just' a duplicate request for query support it was asking how people do things like that when using Firebase Hosting, which may have a different answer.

And I would hope a serious question would not be close after 30 minutes even if it is 'sort of' a duplicate. Because the fact that I 'can drop to the Firebase API and use it directly' is only an answer if there are examples, patterns or best practices and I just don't see any.

Still in need of support / guidance / info.

Brendan
