### ISSUE TITLE
Delete error

### ISSUE THREAD

**Issue by denzo** [firebase/emberfire#228]
Firstly, I absolutely love Firebase and EmberFire!

Here's a bug I could isolate and reproduce consistently.

Two models 'task' and 'history' where 'history' has a reference to the 'task'.

When task is deleted the history needs to be deleted too.

// pseudo code
1) Delete task
2) Find 'history' entry for that 'task'
3) Delete 'history'

You can view the example and the code via the Chrome dev tools here:
https://emberfire-delete-bug.firebaseapp.com

**Comment by tstirrat** [comment]
Thanks a heap for the minimal example app. This will be a great help!

**Comment by tstirrat** [comment]
Because history `belongsTo` task, and you have not defined an inverse relationship, you'd need to delete the history item first.

What appears to be happening in your demo is when you `destroyRecord` on the task, it is removed from the store before you try to delete the history. Now, when trying to `destroyRecord` on the history it thinks it's in an unloaded state because there is a belongsTo with `async: true` and no valid record in the store .. here `ember-data`, not `emberfire`, decides you want to refresh that relationship and does a `find()`. emberfire adapter tells it that there is nothing with that id to refresh.

I did some testing. if you `deleteRecord` on the task first, which does not remove it from the store yet, things work fine.

```js
task.deleteRecord();
history.destroyRecord()
  .then(function () {
    return task.save();
  })
  .then(function (t) {
    console.log('deleted task', t);
  })
  .catch(function (error) {
    console.error(error);
  });
```

but ultimately, just destroy the history first.

```js
history.destroyRecord()
  .then(function () {
    return task.destroyRecord();
  });
```
