### ISSUE TITLE
Feature Comparison to AngularFire... what is missing from EmberFire

### ISSUE THREAD

**Issue by brendanoh** [firebase/emberfire#239]
I am under the impression that AngularFire includes AUTH and Presence (and Idle) features that I personally feel are vital in getting the most out of Firebase.

@tstirrat @sararob are either of these in your plans for EmberFire?

Currently I am using ToriiFire for managing social logins but it actually has some issues. Since login and presence are so tightly bound I really feel like either within EmberFire ala AngularFire or a separate Firebase supported Add on would be the way to go here.

Thoughts? Comments?

**Comment by codepreneur** [comment]
I just write pure firebase code for authentication and social logins... It's fairly straight forward, I can share my implementation.

**Comment by brendanoh** [comment]
@codepreneur I would love to see what you are doing especially relating to Presence. I have some similar things I could share as well.

Presence is the key to Real-time apps IMO. I feel that making that dead simple for EmberFire users to implement would go a long way towards increasing uptake on Emberfire and make Firebase stronger within the Ember community.

**Comment by tstirrat** [comment]
My initial thoughts on auth is that we should embrace the emerging conventions in the Ember community. e.g. Where do we store the session state? How does one enforce access control to a route?

These are problems that are already being solved out there with `ember-simple-auth`/`torii`.

At the very least, we should question whether auth falls under "emberfire" or a separate addon. Currently, `emberfire` is *specifically* an ember-data addon.

`torii-fire` is a good start, I'd prefer we collectively put some effort into that, rather than fragment into another project. `ember-simple-auth` also wraps `torii`. What were the problems you faced with it?

Presence, on the other hand is usually achieved with `onDisconnect`. I do have plans to [allow access to a model's firebase ref](https://github.com/firebase/emberfire/issues/173) for exactly this reason.

It's hard to make an API that makes sense to everyone because the needs of onDisconnect are not always just about presence. e.g. AngularFire doesn't provide an onDisconnect pattern that I am aware of (correct me if I am wrong)

If you have an idea of an API to do presence that makes sense within Ember Data conventions, I'm definitely keen to start a conversation.

Also, can you clarify what you mean by "idle"?

**Comment by oskarrough** [comment]
Just one to second the idea of embracing the tools for auth already out there like torii and ember-simple-auth.

**Comment by brendanoh** [comment]
@tstirrat I am not expecting a full session state manager. In fact what I really want is promise based primitives that can be used by something like Torii-fire. Re: Idle I was referring to https://www.firebase.com/js/libs/idle.js as referenced in https://www.firebase.com/blog/2013-06-17-howto-build-a-presence-system.html. I hadn't seen the https://github.com/firebase/emberfire/issues/173 thread. Helpful to read. 

@oskarrough I really do not understand how "embracing the tools for auth already out there like torii and ember-simple-auth" solves anything. They are fine tools and using Torii-fire was helpful but the part of all this that needs work is the Firebase part. 

IMO using AUTH via a real-time system like Firebase has very limited value if you do not have Presence built into it. I have been walking through building presence into Moai https://github.com/brendanoh/moai/blob/master/app/services/presence.js and I just really wish there was more established patterns to follow. 

Torii-fire does the initial login fine but on refresh it should do an AuthWithToken call to reestablish the session state. If there was an EmberMixin that had Promise wrapped versions of all the FB specific calls that would be perfect.

In general this Q was just trying to see whether EF and AF are supposed to be the same thing and if not how to ensure FB has the right set of tools.

**Comment by tstirrat** [comment]
I started trying to think of a way to do `onDisconnect` things in the model definition:

```js
var User = DS.Model.extend({
  name: DS.attr(),
  lastOnline: DS.attr('timestamp', { onDisconnect: 'remove' })
});
```

And then realised that you only want this for the current user model, not every model in the system. So I think exposing the `record.ref()` is the simplest and most powerful way.

```js
currentUser.ref().child('lastOnline').onDisconnect().set(Firebase.ServerValue.TIMESTAMP);
```

As for idle stuff. again, acting on a single model, so it doesn't make sense to create some complex definition syntax for it. You'd probably make an idle service, access `session.currentUser` and do the setting and getting there.

I'm not seeing a clear way to build presence into some auth system.

My initial brainstorm is to specify a `presenceProperty` in the `torii-fire` config that automatically wires up the `onDisconnect`. Even then.. how do you get the record specific ref so that you can call `.child(presenceProperty)` on it? Do we assume `user` record has a `.ref()`?  what if they don't use firebase for their user record?

Also, some will want online/offline. Others will want `lastOnline` timestamps.

How do you see presence being configured if we did include some primitives?

**Comment by brendanoh** [comment]
@tstirrat : *then realised that you only want this for the current user model, not every model in the system.*

Actually we need the data for every user model but I only need to manage for the current user. As I need to know whether others are online not myself. 

My thoughts are we conceptually split this into two parts,

1. Primitives to keep the logged in user's `lastOnline` synced with FB user. This is where this comes into play:
`currentUser.ref().child('lastOnline').onDisconnect().set(Firebase.ServerValue.TIMESTAMP);` 

Additionally, I think we would need a similar `lastActivity` property which holds the last time the user has made a request or saved a piece of data. If we have those two then #2 seems simpler.

2. Properties on a user that other users can access to determine their state. I think this should be a `PresenceMixin` like below:
```
// PresenceMixin
import Mixin    from 'ember/mixin';
import Firebase from 'firebase';

export default Mixin.create({
  idleTimeInMs: 300000, // 5 minutes default but mixin class can override

  // TIMESTAMP of the last time they were seen online --> Their disconnect time really
  lastOnline: function(){
     return new Date(); // FB magic goes here
  }.property(),

  // TIMESTAMP of the last action taken proactively by them
  lastActivity: function(){
     return new Date(); // FB magic goes here
  }.property(),

  online: function(){
    var lastActivity = moment(this.get('lastActivity'));
    var lastOnline   = moment(this.get('lastOnline'));
    if(!lastActivity || !lastOnline || lastOnline > lastActivity) {
      return 'offline';
    } else if (lastActivity.add(this.get('idleTimeInMs'), 'ms') > moment(Firebase.ServerValue.TIMESTAMP)) {
      return 'online';
    } else {
      return 'idle';
    }
  }.property('lastActivity', 'lastOnline')
});
``` 

This way everyone gets the data they need for their usage but it remains pretty simple to use or extend.

Thoughts?

**Comment by brendanoh** [comment]
@tstirrat if my previous comment makes sense and you can help me with it I will put together and maintain an `emberfire-presence`  ember-cli addon for people to use.

**Comment by tstirrat** [comment]
> Actually we need the data for every user model but I only need to manage for the current user. As I need to know whether others are online not myself.

Yup, that's what I was saying: you can't define presence primitives (e.g. `onDisconnect`) in the model definition because it relates to **all** models in your local cache. You don't want every model in your cache to do an `onDisconnect` call when you disconnect otherwise every user becomes "offline" when any client app disconnects.

Instead, you want to manage presence from the single user model that represents your currently logged in user. This is difficult to make both *generic* and *useful*. It's why I think exposing the `record.ref()` is a good start.

In regards to your mixin, it's a nice idea. However, I think this kind of thing is very app specific. e.g. If I was creating a chat app I would likely use a single field of `status` that has the possible values: `online`, `idle`, `away`, `dnd`, `offline`. All of which are managed by some custom app logic, incl. some use of [idle.js](https://github.com/shawnmclean/Idle.js), and use of `record.ref().onDisconnect()`

In another app I might only care about `online`, another I might care about `lastActivity`.

The location where I set up the `onDisconnect` pattern is the same place I'd set up the `idle` logic. In fact, the model definition (or a model mixin) is not the right place to store this idle/presence logic. It is application logic, not model definition.

Maybe something that is not specifically tied to emberfire makes more sense.. e.g. `ember-presence` or `ember-idle` that build on top of [idle.js](https://github.com/shawnmclean/Idle.js/blob/master/build/idle.js):

```js
afterLogin() {
  currentUser.set('status', 'online').save().then(function () {
    // handle offline
    currentUser.ref().child('status').onDisconnect().set('offline');
  });
  
  // idle  = idle for 5 secs
  this.get('presence').onIdle(5000, function () {
    return currentUser.set('status', 'idle').save();
  });
  
  // away = idle for 10 secs
  this.get('presence').onIdle(10000, function () {
    return currentUser.set('status', 'away').save();
  });
  
  this.get('presence').onBack(function () {
    return currentUser.set('status', 'online').save();
  });

  // lastActivity
  this.get('presence').onActivity(function () {
    return currentUser.set('lastActivity', Firebase.ServerValue.TIMESTAMP).save();
  });
} 
```

I'd love to hear some other folks chime in on this.

**Comment by codepreneur** [comment]
@brendanoh https://github.com/embersherpa/embercises/blob/master/app/services/auth.js

**Comment by brendanoh** [comment]
> Instead, you want to manage presence from the single user model that represents your currently logged in user. 

I would suggest this to be a mixin to the **controller** or **service** that manages session state and not a model at all.

> This is difficult to make both generic and useful. It's why I think exposing the record.ref() is a good start.

Based on having a mixin in the user model to access this data then I would think only things required in the mixin would be `lastActivity` and `lastOnline` (really last disconnect). Everything else seems calculable from that I think. See comment below.

> In regards to your mixin, it's a nice idea. However, I think this kind of thing is very app specific. e.g. If I was creating a chat app I would likely use a single field of status that has the possible values: online, idle, away, dnd, offline. All of which are managed by some custom app logic, incl. some use of idle.js, and use of record.ref().onDisconnect(). In another app I might only care about online, another I might care about lastActivity.

I wasn't suggesting a finished implementation. The only things required in the mixin would be `lastActivity` and `lastOnline` (really last disconnect). The online was a simple sample of how to do your own implementation.

**Comment by tstirrat** [comment]
- Auth is coming when torii-fire merges in #256 , we can then manage auth and improve the developer experience under the emberfire repo
- Presence is doable since #249 (1.4.6)

  ```js
  currentUser.ref()
    .child('status').onDisconnect().set('offline');
  ```

**Comment by ewaschen** [comment]
Hi, for the presence, has this been noted anywhere in the docs?  Can't find anything about it.  I'm asking because I am trying to do a presence system for a chatroom.  Essentially I have urls such as cr/-K_-rrhedUJColu4ynwC/ with each on representing a chat roon, so with emberfire or firebase is there a way I can use presence just to see how many people on on this page? or it is not possible.

Thanks

**Comment by brendanoh** [comment]
This is what I do:
```
  model: function() {
    const sid = this.get('session.uid');
    if(sid) {
      return this.get('store').findRecord('person', sid).then(function(person) {
        person.set('online', true);
        return person.save().then(function(person) {
          person.ref().child('online').onDisconnect().set(false); 
          return person;            
        }); 
      });  
    }
  },
```

**Comment by ewaschen** [comment]
@brendanoh @tstirrat  Hi, Thanks for your reply, I  didn't realize that once I navigate to a different page even if its on the same website, the onDisconnect fires and reports status to false.  I thought I had to disconnect from the entire website completely.  This is exactly what I need! thanks

**Comment by Cryrivers** [comment]
@ewaschen no, `onDisconnect` 'fires' when a user disconnects from Firebase (no matter how he/she does it, e.g closing the browser window, disconnecting wifi connection, power outage etc.)

I quoted `fire` because I believe it happens on firebase instead of browsers.

**Comment by ewaschen** [comment]
@Cryrivers So is it possible to use firebase to update when the route changes, or will I have to do that myself

**Comment by Cryrivers** [comment]
@ewaschen I think you have to do it by yourself, in Routes' `activate`, `deactivate` hooks.

**Comment by ewaschen** [comment]
@Cryrivers tried that, works if I change routes like from 
`cr/-Kd7SH_ZMno to /create`
but not from 
`cr/-Kd7SH_ZMno to /cr/-Kct_XIttt9`

The latter situation is what I need.
