### ISSUE TITLE
Auth with emberfire and firebase's email + password auth.

### ISSUE THREAD

**Issue by BrianTMaurer** [firebase/emberfire#306]
I am using ember v1.13.7 + emberfire v1.5.0 + firebase v2.1.0 and the basic firebase auth (email, password)

For some reason when I try to login using:
```javascript
this.get('session').open('firebase', {
  provider: 'password'
  email: this.get('email')
  password: this.get('password')
})
```
I get the following error:
`Error: Unknown Event: failOpen for: <StateMachine currentState:'authenticated’ >`

By the way, I am just following the guide: https://www.firebase.com/docs/web/libraries/ember/guide.html#section-authentication (edited)

**Comment by tstirrat** [comment]
Hi Brian, thanks for the report.

The error suggests you are already in an `authenticated` state. Are you trying to call `open` when you are already logged in? If so, do a session `close` to log out before doing another `open`.

Otherwise, are there any logs in the console before the one you listed?

Finally, we updated our docs recently because some users were getting a [different error](http://stackoverflow.com/questions/32023653/emberfire-authentication-and-toriifirebaseadapter/32079863#comment52273121_32079863). 

Your application route should **return** the session `fetch` promise like so:

```js
// app/routes/application.js
import Ember from 'ember';
export default Ember.Route.extend({
  beforeModel: function() {
    return this.get("session").fetch().catch(function() {}); // <--- note that we now return the promise here
  }
});
```

**Comment by BrianTMaurer** [comment]
Thanks, I was already authenticated as the error clearly states. Classic late night debugging failure to read closely. Apologies – Brian.

**Comment by tstirrat** [comment]
No problems, glad it's working again :)

**Comment by adjohnson916** [comment]
@BrianTMaurer Hah, I just came across this on my own - having the same error.
