### ISSUE TITLE
Deleting property doesn't sync

### ISSUE THREAD

**Issue by IsaiahJTurner** [firebase/emberfire#315]
If a key/value is deleted within the model from another client, EmberFire won't update.

Looking at the websocket frames, it is receiving the updated value as `null` but the data isn't updating to show that the record was deleted.

## Expected behavior
My talkstatus before: 
```
{
  slides: 4,
  isLive: true
}
```
Now I remove the slides property from a different client.
My talkstatus after:
```
{
  isLive: true
}
```

## Actual behavior
My talkstatus before: 
```
{
  slides: 4,
  isLive: true
}
```

Now I remove the slides property from a different client.

My talkstatus (as shown by Ember but not correct) after: 
```
{
  slides: 4,
  isLive: true
}
```
 I see these events but the null event is not changing anything in Ember.
`{"d":{"b":{"p":"talkstatuses/55fc4078e057c1bc1caa4ae2/slides","d":4},"a":"d"},"t":"d"}`
`{"d":{"b":{"p":"talkstatuses/55fc4078e057c1bc1caa4ae2/slides","d":null},"a":"d"},"t":"d"}`

**Comment by tstirrat** [comment]
Hrm, thanks for this report. Will look into it!

**Comment by IsaiahJTurner** [comment]
Any news on this? I tried looking into it myself and couldn't figure it out.

**Comment by tstirrat** [comment]
I can look into this soon.

It will be related to the `store.push` in [_handleChildValue](https://github.com/firebase/emberfire/blob/1fd592e4f56762807e8c882096e22b4f3cf95e31/addon/adapters/firebase.js#L349-L350).

My guess is that the new data given by firebase doesnt include the slides property .. even though it is sent on the wire as null, it might be omitted in the 'value' payload (because properties set to null are omitted in firebase in general)
