### ISSUE TITLE
Add support for authWithOAuthRedirect

### ISSUE THREAD

**Issue by rmmmp** [firebase/emberfire#341]
Is there any reason why `authWithOAuthRedirect` is not supported in emberfire? If none, then I think it should be added as a fallback when `authWithOAuthPopup` doesn't work.

As said in the Firebase docs:

> Browser popups and redirects are not available on all platforms or browser environments. Popups are not available in Chrome for iOS, iOS Preview Panes, or local, file:// URLs. Redirects are not available in PhoneGap / Cordova, or local, file:// URLs. Therefore, it is recommended that you use a combination of both authentication methods to cover all environments.

**Comment by tstirrat** [comment]
I think the main reason is that the Torii state will be lost due to the redirect.. there was discussion of using an iframe to handle this [here](https://github.com/Vestorly/torii/issues/203) but nothing seemed to come of it.

**Comment by sgasser** [comment]
Are there other solutions then an iframe?

Creating a EmberFire-App with auth it's not working on iOS, Firefox Mobile etc... :-1:

**Comment by tstirrat** [comment]
The Torii provider uses `ref.getAuth()` to determine if there is an existing session. Theoretically, you should be able to manually call log `ref.authWithOAuthRedirect` have the remainder of the Torii session work as normal:

```js
// your login action
actions: {
  login() {
    this.container.resolve('service:firebase').authWithOAuthRedirect('google', function(error) {
      if (error) {
        // handle pre-redirect error
      }
    });
  }
}

// page redirects and logs in

// app/routes/application.js
beforeModel() {
  return session.fetch()
    .catch(e => {}); // swallow error, allows app to boot when no user was logged in
}
```

**Comment by rmmpaderes** [comment]
Currently I've modified `addon/torii-providers/firebase.js` to do a `authWithOAuthRedirect` as a fallback when `authWithOAuthPopup`. Works fine except for what you've pointed above.

In our case, after a successful login, it should then redirect to a different route. But because `authWithOAuthRedirect` loses the state of the original window, it won't redirect but the session does get saved. So a simple, re-click of Sign in with Facebook or re-opening the app does the trick. The flow is bad but it beats not being able to sign in at all. I guess we're stuck with the workaround until torii figures out how to handle this.

**Comment by tstirrat** [comment]
Yeah, the problem is that there is no success callback, so there is no way for the `open` method to know if the login succeeds.

Instead, you would only know about the login via session.fetch() at the start of the app after redirect. You could probably use something like `localStorage` to store a temp variable which will inform you after the refresh if the user just attempted a login (and then clear the temp variable). 

All of this is an app concern and would be difficult to implement in a reusable way in Torii or the adapter.

**Comment by tstirrat** [comment]
We could perhaps provide a way to request the redirect version:

```js
this.get('session').open('firebase', { provider: 'google', redirect: true });
```

But the rest of the implementation would rest on the developer.

Your implementation could be something like:

```js
const LS_AUTH_FIRST_TIME = '__some-unique-key';

// action
localStorage.setItem(LS_AUTH_FIRST_TIME, true);
this.get('session').open('firebase', { provider: 'google', redirect: true });

// route
beforeModel() {
  this.get('session').fetch()
    .then(() => {
      if (localStorage.getItem(LS_AUTH_FIRST_TIME)) {
        localStorage.removeItem(LS_AUTH_FIRST_TIME);

        // redirect to your welcome route here
      }
    })
    // pass through unauthenticated sessions
    .catch(() => {});
}
```

**Comment by tstirrat** [comment]
#344 adds the redirect functionality

```js
this.get('session').open('firebase', { provider: 'google', redirect: true });
```

**Comment by rmmpaderes** [comment]
I think a better way to handle the redirect is the use the build-in redirect() itself in an Ember route. Something like this:

```javascript
beforeModel() {
  return this.get('session').fetch().catch(function() {});
},

redirect() {
  if (!this.get('session').get('isAuthenticated')) {
    this.transitionTo('login');
  }
}
```

But anyway, I guess that's a discussion for another day.

Hmm, so with
```javascript
this.get('session').open('firebase', { provider: 'google', redirect: true });
```
You're basically giving us the option to go full `authWithOAuthRedirect` rather than a `authWithOAuthPopup`. Since the state will get lost on a `authWithOAuthRedirect`, there would be no purpose on using it (or perhaps the use of it would be less). But if a developer is so eager to use it, wouldn't it be better for emberfire to set it up as an automatic fallback for `authWithOAuthPopup` in-case that doesn't work?

**Comment by tstirrat** [comment]
I'm giving the ability to programatically select redirects. The rest is up to the developer to work out what works and what doesn't for certain platforms.

Given that you lose app state, I don't think an auto-fallback option is doable -- it does not have feature parity with popups.

Use `redirect: true` at your own peril. The only reason I added it, is so that you don't need to manually get the ref and call the function yourself.
