### ISSUE TITLE
Could not find module `emberfire/adapters/firebase` 

### ISSUE THREAD

**Issue by ThomasLiu** [firebase/emberfire#375]
Uncaught Error: Could not find module `emberfire/adapters/firebase` imported from `linkee-before/adapters/application`

![img1](http://7xoktu.com1.z0.glb.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202016-03-05%20%E4%B8%8B%E5%8D%888.24.03.png)

![img2](http://7xoktu.com1.z0.glb.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202016-03-05%20%E4%B8%8B%E5%8D%888.23.22.png)

![img3](http://7xoktu.com1.z0.glb.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202016-03-05%20%E4%B8%8B%E5%8D%888.26.34.png)

![img4](http://7xoktu.com1.z0.glb.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202016-03-05%20%E4%B8%8B%E5%8D%888.34.05.png)

**Comment by ThomasLiu** [comment]
oh ~ when i run the code 'ember build --prod' , it's working

**Comment by pixelpax** [comment]
Hey, I realize this is closed, but I came here for a similar probelm--

Note that you have to rerun `ember server` in order to load changes from the config file. 

That was the problem for me. For anyone with the same problem as @ThomasLiu, make sure that you're attaching the config attribute in the original definition of ENV (or in whichever environment specific configuration you intend to use it)

**Comment by steven-github** [comment]
`ember install ember-cli-shims` should do the trick.
