### ISSUE TITLE
Feature Request : Being able to define a base path on adapters

### ISSUE THREAD

**Issue by olivierchatry** [firebase/emberfire#430]
Hello,

I think it would be a good idea to be able to define a **base path** on adapters. 
For example, let say you have a model that is a project, each project contains multiple different data and models. 

With the current emberfire, every model would be stored flat at the roots of Firebase. It would be cool if it would let me store the data into a path, say for example : 

```
+-projects
+--[generated_uid_project]
+----somedata

+-projectDatas
+--[generated_uid_project]
+----users
+------[generated_uid]
+----datas
+------[generated_uid]
+------[generated_uid]
```

To achieve that, it means that each adapters should be able to have a base path. As far as the code is concerned, it seems that we only need to change `pathForType` @ https://github.com/firebase/emberfire/blob/master/addon/adapters/firebase.js#L633

What do you think ?

**Comment by jamesdaniels** [comment]
Hey Olivier, this seems a reasonable request. Feel free to take a stab @ it and submit a pull request, if you've got the cycles.

**Comment by jamesdaniels** [comment]
Have you tried simply overriding `pathForType` in your adapter? While not dynamic that would give you most of what you're looking for IMO.

**Comment by olivierchatry** [comment]
Yep, I will try there first, but I think it might be something that might interest other people, as it can be an easy way to export / import a bunch of related data.

**Comment by jamesdaniels** [comment]
@tstirrat and I have been chatting and we're working on a proposal that could solve this in a general way. Overriding id on create and passing a firebase ref during query looks like the best direction, thoughts?

Will update as we think on this more.

**Comment by jamesdaniels** [comment]
#432

**Comment by olivierchatry** [comment]
I just read the proposal, it is an interesting way to solve the security issue, but I'm not sure it can apply to what I want to do. My idea was more to have kind of the same functionality as embedded record, but with keeping the async relationship part. It would be easier to *pod* the project.

The big down with what I want to do is that, since adapter are only one per model type, you need to have an *active* project ( so only one loaded at the same time ). It is OK for my work case, and I implemented something similar in the pouchdb ember addon.

**Comment by tstirrat** [comment]
The proposal that I have made will work with `async: true` and will allow deep paths.. so you could nest all your users etc under `/users/:projectId/:id` by setting the id for the record to `:projectId/:id` before saving. I see that it would not specifically allow the structure you listed above..

In the meantime, before we can implement #432 , have you considered using a service to hold the currently selected project? Then you could probably use it inside pathForType in your adapters?

```js
// adapters/data.js
export default FirebaseAdapter.extend({
  currentProject: Ember.inject.service(),
  pathForType(modelName) {
    const projectId = this.get('currentProject').get('id');
    const collectionName = this._super();
    return `projectDatas/${projectId}/${collectionName}`;
  }
});
```

I haven't tried something like this, but in theory it should work as long as you very rarely change the project without reloading the whole app. With this approach, you'd need to `unloadAll` any time you changed the active project.. things could get weird otherwise.

With the proposal in #432 you could do this:

```js
const projectId = project.get('id');

// get data in route
const q = this.get('firebase').child(`datas/${projectId}`).limitToLast(100);
return this.store.query(q);

// save new data
const pushId = this.get('firebase').push().key;
const data = store.createRecord('data', {
  id: `${projectId}/${pushId}`,
  roomId: conversationId,
  body: 'Hello world',
}).save(); // saves at datas/:projectId/:pushId
```

And this would allow finer grained security rules on the data so that a project member could list and query on all data at `/datas/:projectId/`, but someone from another project could not.

We could look at allowing a much more freeform root path in #432 .. but that would require some weird stuff where `pathForType` needs to contain some mutable state (like in the provided workaround above).. This will add unnecessary complexity IMO

**Comment by tstirrat** [comment]
If you have any more suggestions for the proposal, lets talk in #432

**Comment by tstirrat** [comment]
Did you have any success holding the currently selected projectId in a service?

**Comment by olivierchatry** [comment]
Hey ! Sorry, I have to concentrate onigrating our software over Google Cloud, so I did not had time to look at it. I will try probably next week.

**Comment by jamesdaniels** [comment]
I'm going to close for now, feel free to keep discussing here and on #432. If the suggested work-around isn't helping, feel free to reopen.

**Comment by olivierchatry** [comment]
Will do, thanks !
