### ISSUE TITLE
Persistence is unreliable

### ISSUE THREAD

**Issue by jarrodzimm** [firebase/emberfire#461]
```
e.g.
DEBUG: -------------------------------
DEBUG: Ember      : 2.10.1
DEBUG: Ember Data : 2.10.0
DEBUG: Firebase   : 3.6.4
DEBUG: EmberFire  : 0.0.0  (<<<< this doesn't seem to be correct, I'm using 2.0.5)
DEBUG: jQuery     : 3.1.1
DEBUG: -------------------------------
```

### Test case

models/conversation.js
```
export default DS.Model.extend({
  invitees: DS.hasMany('user', { async: true, inverse: 'invitedConversations' })
});
```

models/user.js
```
export default DS.Model.extend({
  invitedConversations: DS.hasMany('conversation', { async: true, inverse: 'invitees' })
});
```

routes/conversation.js
```
export default Ember.Route.extend({
  model(params) {
    return RSVP.hash({
      conversation: this.get('store').query('conversation', {
        orderBy: 'slug',
        equalTo: params.conversation_slug
      }),
    });
  },
  actions: {
    addInvitee(conversation, invitee) {
      conversation.get('invitees').addObject(invitee);
      invitee.get('invitedConversations').addObject(conversation);
    },
    removeInvitee(conversation, invitee) {
      conversation.get('invitees').removeObject(invitee);
      invitee.get('invitedConversations').removeObject(conversation);
    },
    saveInvitees(conversation) {
      conversation.save().then(() => {
        conversation.get('invitees').forEach((invitee) => {
          return invitee.save();
        });
      });
    }
  }
});
```

I have a component that uses [`route-action`](https://github.com/DockYard/ember-route-action-helper) to call `addInvitee`, `removeInvitee` and `saveInvitees`.

### Steps to reproduce

1. With both `conversation.invitees` and `user.invitedConversations` empty, I call `addInvitee` to add a dirty many-to-many relationship
2. Call `saveInvitees` to persist
3. Records are saved correctly
4. Delete the `conversation.invitees` and `user.invitedConversations` in the Firebase console for testing to simulate activity on the records
5. My app sometimes shows me `conversation.invitees` and `user.invitedConversations` are empty (which is correct) or sometimes shows me they are not empty (which is not correct) – both scenarios have occurred while testing
6. In either case, calling `saveInvitees` again does not persist any changes on save

### Expected behavior

When I make changes in the Firebase console, the many-to-many relationships in my app should refresh to reflect the current state, which would allow me to save new relationship changes

### Actual behavior

Relationship data is only saved the first time (after I've refreshed the page, called `addInvitee`, then `saveInvitees`). Once I manually delete `conversation.invitees` and `user.invitedConversations` in the Firebase console (basically resetting my state), nothing is being persisted from my app when I call `saveInvitees` again (which calls `save` on each record). My guess is the dirty many-to-many relationships are causing confusion.

**Comment by jarrodz** [comment]
I'm running into this same problem without the Firebase console, testing instead with several browsers. I've logged into my app as two different users in two different browsers (Chrome and Firefox). Sometimes, if I add an object to a belongsTo/hasMany relationship in one browser, it will appear in the second, because I've saved and it persisted. Other times, for no rhyme or reason, it won't appear in the second browser, because, even though I've saved, it doesn't persist. Same with removing an object: sometimes it appears in the other browser, if it persisted. The problem is, in the browser where I am adding/remove the object from the relationship, it looks like it was successful after a save (the object appears or disappears from the list). But when I compare the state in the browser with the state of my persisted data in the Firebase console, it doesn't match.

I wish Ember had an `hasDirtyRelationships` property. That would make this easier to test. But I know `save` is successful, because of the Promise it returns.

Any help would be greatly appreciated.

**Comment by jarrodz** [comment]
Actually, I'm wondering if I started running into issues because I set all of my inverses to `null`. I'll follow #468 to see if `inverse: null` is still the best way to set up relationships for Emberfire.

**Comment by Suven** [comment]
Hey!

I noticed some things about your example and thought it might be useful sharing this, since I did not experience this unrelieability you are describing.

```
export default Ember.Route.extend({
  model(params) {
    return RSVP.hash({
      // Should be unrelated, but why aren't you using findRecord instead?
      conversation: this.get('store').query('conversation', {
        orderBy: 'slug',
        equalTo: params.conversation_slug
      }),
    });
  },
  actions: {
    addInvitee(conversation, invitee) {
      conversation.get('invitees').addObject(invitee);
      invitee.get('invitedConversations').addObject(conversation);
      // You did not persist your changes here. Keep in mind that you need to persist both
      // sides of the relationship via .save(). That's because firebase's db does not know
      // anything about relationships.. i.e: also save the conversation
    },
    removeInvitee(conversation, invitee) {
      conversation.get('invitees').removeObject(invitee);
      invitee.get('invitedConversations').removeObject(conversation);
      // You did not persist your changes here. Keep in mind that you need to persist both
      // sides of the relationship via .save(). That's because firebase's db does not know
      // anything about relationships.. i.e: also save the conversation
    },
    saveInvitees(conversation) {
      // In my opinion that is a dangerous order. You should first save all invitees (to make sure
      // they are available and then save the conversation itself.
      conversation.save().then(() => {
        conversation.get('invitees').forEach((invitee) => {
          return invitee.save();
        });
      });
      // As an example:
      RSVP.all(conversation.get('invitees').invoke('save'))
          .then(() => conversation.save());
    }
  }
});
```

**Comment by jarrodz** [comment]
@Suven I really appreciate you looking over my issue. Allow me explain some the logic behind it.

```
// Should be unrelated, but why aren't you using findRecord instead?
conversation: this.get('store').query('conversation', {
  orderBy: 'slug',
  equalTo: params.conversation_slug
})
```
I'm using query because the URL slug is different than the record ID, which I did intentionally to not expose the ID. The ID may be something like `-KXxWfYugSXnShCtwis-` and the slug something like `Q0lp5URE2w`, so my URL looks like `/user/Q0lp5URE2w` instead of `/user/-KXxWfYugSXnShCtwis-`

```
addInvitee(conversation, invitee) {
  conversation.get('invitees').addObject(invitee);
  invitee.get('invitedConversations').addObject(conversation);
  // You did not persist your changes here. Keep in mind that you need to persist both
  // sides of the relationship via .save(). That's because firebases db does not know
  // anything about relationships.. i.e: also save the conversation
},
removeInvitee(conversation, invitee) {
  conversation.get('invitees').removeObject(invitee);
  invitee.get('invitedConversations').removeObject(conversation);
  // You did not persist your changes here. Keep in mind that you need to persist both
  // sides of the relationship via .save(). That's because firebases db does not know
  // anything about relationships.. i.e: also save the conversation
}
```

I didn't persist because these actions make changes on the client only. I'm letting the user add and remove invitees, and once they are ready to send invites (persist), I call `saveInvitees`. Though the action isn't included above, I have `rollbackInvitees` for when the user cancels their changes.

As for `saveInvitees`, I took your advice and used `RSVP.all`. That worked very well for saving – thank you.

I'm still running into problems though when I delete from another browser (either using my app on a different browser or using the Firebase console to browse the data). If I delete invitees from the database (both sides of the relationship), it disappears from my Ember app list (as expected), but when I try to re-invite the same invitee, it doesn't persist (though my app tells me it has). If I refresh the browser, then it works. So I'm thinking this is a cache issue, but I'm not sure.

This is happening throughout my app, not just in the example above. If I remove a relationship in one browser and try to re-add it in the other browser, it won't persist. When I refresh the other browser, then it allows me to persist.

**Comment by woohoou** [comment]
Same here, just cannot make a simple has many call with { async: true, inverse: null } relationship definition, tried with or without inverse: null.

**Comment by jamesdaniels** [comment]
Thanks for all the info @jarrodz I was planning on digging in on some of this, but still catching up from the xmas vaca backlog. I'll see if I can repro what you're seeing and either squash some bugs or give you a work around.

**Comment by jarrodz** [comment]
@jamesdaniels Thank you, much appreciated
