### ISSUE TITLE
Make work with ember-data-fastboot

### ISSUE THREAD

**Issue by rwwagner90** [firebase/emberfire#465]
Would love to have compatibility with https://github.com/cardstack/ember-data-fastboot for shoebox capabilities.

**Comment by erkarl** [comment]
I'm facing the same issue when experimenting with emberfire + fastboot and I haven't figured out yet how to properly shoebox the data. 

For now I've implemented an ugly hack to disable loading action for the initial load after fastboot so that for the enduser it looks like the model doesn't reload.

**Comment by rwwagner90** [comment]
I think emberfire either has to be JSONAPI or we have to work on some sort of adapter or something.
