### ISSUE TITLE
abandonware?

### ISSUE THREAD

**Issue by jmonster** [firebase/emberfire#562]
This project is the only reason Firebase is appealing to me. I’m about to start on a new project and torn between the head start emberfire provides and the risk of using what appears to have been abandoned.

Is this project going to be revisited or should I move on?

Thank you 🙏

**Comment by oliw** [comment]
![image](https://user-images.githubusercontent.com/1246970/49420014-4d32ad80-f73e-11e8-8688-e924f9febbd1.png)

**Comment by brendanoh** [comment]
I have used EmberFire in a dozen projects over the years and the combo of EmberData and Firebase is perfect for startups.

I would love to see this repo come back to life but there are about 8 business days left in the 4th quarter so a release seems incredibly unlikely, especially with 6 months having passed since https://github.com/firebase/emberfire/pull/553.

I understand @jamesdaniels has other priorities but the last year has been completely discouraging for any of us that want to be able to count on EmberFire.

@oliw when was that conversation?

**Comment by zoltan-nz** [comment]
@sjmaceyful Totally agree. It would be great if this package would be maintained. As I suggest in the most popular free [Ember.js tutorial](https://yoember.com) ([yoember.com](https://yoember.com)), the best what we can do at the moment to use the latest LTS version of Ember. Ember.js version 3.4 is still compatible with the latest stable EmberFire.

@jamesdaniels Please let us know how could we help. I see you had a great progress on your v3 branch. The awesome Ember community is here and happy to give a hand. ;)

**Comment by brendanoh** [comment]
@sjmaceyful @zoltan-nz 

I have done over a dozen presentations about Firebase and Emberfire over the past 4 years and I have personally introduced hundreds of developers and startups to Firebase and especially Emberfire.

My utter frustration with the virtual if not literal abandonment of this repo reminds me of a quote from Maya Angelou. 

> "When someone shows you who they are, believe them"

The Firebase team has unfortunately showed us that the **emberfire repo** and **emberfire community** are not important to them. This is not me _throwing shade_, this is the only rational conclusion one can come to by the way this repo has been left to languish for what seems like two years. 

How could any developer nowadays recommend Firebase for an Ember app?

**Comment by bnetter** [comment]
This issue deserves to be reopened I think… 😠
