### ISSUE TITLE
Emberfire seems to be abandoned

### ISSUE THREAD

**Issue by brendanoh** [firebase/emberfire#563]
There are many disheartened Emberjs developers who feel that Firebase has abandoned the "Official Ember Data adapter for Firebase". I think I can speak for many of us by saying that we love Firebase but are increasingly frustrated. 

An issue was opened in Github more than 2 months ago asking if the Emberfire project had been abandoned.

https://github.com/firebase/emberfire/issues/562

There have been zero responses from anyone from Firebase/Google. 

Saying that the "Emberfire repo seems to be abandoned" is not a complaint by an ungrateful developer or me throwing shade, it is the only rational conclusion one can come to by the way this repo has been left to languish for what seems like two years. The fact is the Emberfifre code base most of us are using hasn't been changed substantially since Apr 26, 2017.

James Daniels has a PR opened from 7 months ago that also seems to have been abandoned or at very least deemed so unimportant as to be left unfinished without even an status update in over 3 months.

https://github.com/firebase/emberfire/pull/553

So I guess I am asking for the EmberFire community: 

If EmberFire hasn't been abandoned then can we get an actual update?

Cross posting in the Firebase Google Group

**Comment by tastebud** [comment]
brendanoh thanks for your efforts to get a status on Emberfire from the Firebase team.  I am also a huge fan of Firebase and have not found a faster way to a robust backend.

**Comment by conormag** [comment]
I would like to echo the previous sentiments wholeheartedly. I did notice that James seemed to have created a new branch (v3-scratch) that has some more recent activity (around a month ago). 

Unfortunately, he doesn't seem to engage on this project anymore - either here or on twitter. There is also an open query on the firebase's ember slack channel that wasn't responded to either.

Would just be good to get some sort of official statement one way or another. I'm really struggling to evangelize firebase in my company when we're stuck in this state.

**Comment by davideast** [comment]
@tastebud I'm going to wait for @jamesdaniels full response here, but you have the wrong metrics.

You need to search for `@angular/fire` instead of `angularfire`. You can also include the deprecate package of `angularfire2` and you would get ~55k downloads per month instead of 1,441.

**Comment by jmonster** [comment]
I say this with utmost kindness and respect — but Google has some deep pockets, why not hire an extra hand to help you? If they offered remote I’d *immediately* apply myself. And of course I realize you have to weigh out the value proposition as you just did, and it’s great you’re sharing all that with us, but I think it’s largely about marketing and gaining new users. Googs shouldn’t expect this to be a profit center, at least not without more marketing effort behind its existence at all. I think Ember and Firebase really offer something combined that hugely outweighs the sum of parts. It’s the new rails 15 minute blog story, only way way way better.

I love Firebase but it’s only because of your hard work on this addon that it offers me any real value. So, forget everything else, thank you for your contributions here. I learned a lot even if I have to reconsider my infrastructure and write a server eventually.

**Comment by jamesdaniels** [comment]
Thanks @jmonster. 

Obviously can't speak to how things work internally; but if it blows up like that it will probably get more resources 😜 Has a couple orders of magnitude and some more low hanging fruit to go before that conversation though. So tell ya friends, do a lightning talk at your local Meetup, etc. 😉

Hoping v3 gets us further along.

**Comment by maximilianmeier** [comment]
@jamesdaniels first thanks for your contributions. 

The biggest problem for me was not that there is no active development. But I missed the Firestore so much. The Ember Data Adapter for the Realtime Database worked so good. And something like that for the new Firestore database would be just amazing.
